# Generated by Django 3.1 on 2020-08-19 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricewatch', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricewatch',
            name='Alumahan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Ampalaya',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Banana_Lakatan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Banana_Latundan',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Bangus',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Cabbage',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Calamansi',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Carrots',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Chayote',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Chili',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Eggplant',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Ginger',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Habitchuelas',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Galunggong',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Garlic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Premium',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Red_Onion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Regular_milled',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Special',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_Well_milled',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Imported_White_Onion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Galunggong',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Garlic',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Premium',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Red_Onion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Regular_milled',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Special',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_Well_milled',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Local_White_Onion',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Mango',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='NFA',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Papaya',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Pechay',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Sitao',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Squash',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Tilapia',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='Tomato',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='White_Potato',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pricewatch',
            name='province',
            field=models.CharField(blank=True, max_length=30, verbose_name='Province'),
        ),
    ]
